### PR TITLE
Minor updates to contributing and license validation

### PR DESCRIPTION
**Pull request by gj**
Hey @SophieDeBenedetto,

Do you mind if I take over maintenance of this gem?

### CODE REVIEW

**Comment by adamjonas** [comment]
@gj Sophie doesn't work here anymore. Feel free to dive in.

**Comment by gj** [comment]
@adamjonas afaik, she has to `gem owner -a` someone to add a new owner — she's the only one w/ access at the moment.

**Comment by adamjonas** [comment]
I'll reach out to her

**Comment by AspenJames** [comment]
I just noticed this PR also fixes #8, making #9 unnecessary 
@adamjonas @gj

**Comment by sgharms** [comment]
Massive refactor coming. Closing

**Pull request closed without merging**
